package question;

public enum TestCategory {
	
	ELIMINATE_NEGATION,
	REDUCE_NEGATION_COUNT,
	REDUCE_NEGATION_COUNT_INCREASE_NEGATION_LEVEL_TRADEOFF,
	REDUCE_NEGATION_LEVEL,
	REDUCE_OPERATOR_COUNT,
	REDUCE_OPERATOR_NESTING,
	REDUCE_OPERATOR_NESTING_INCREASE_OPERATOR_COUNT_TRADEOFF_CNF,
	REDUCE_OPERATOR_NESTING_INCREASE_OPERATOR_COUNT_TRADEOFF_DNF;
}